#pragma once

#include "NativeGameplayTags.h"

/** Declares the "Vital Attributes" gameplay tag. */
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Vital_VitalityMatrix)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Vital_EnergeticEndurance)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Vital_ArcaneReservoir)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Vital_DefensiveSynchrony)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Vital_BarrierMatrix)

/** Declares the "Primary Attributes" gameplay tag. */
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Primary_Physique)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Primary_Adaptivity)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Primary_NeuralAgility)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Primary_EmpathicResonance)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Primary_EssenceControl)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Primary_Nanomancy)

/** Declares the "Secondary Attributes" gameplay tag. */
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_VMCapacity)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_VMRecovery)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_EECapacity)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_EERecovery)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_ARCapacity)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_ARRecovery)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_KineticAbsorption)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_NanoshieldThreshold)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_ResonanceSyncQuality)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_ResonanceAmplification)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_EmpathicInfluence)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_TechnologicalInterface)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_SignalStealth)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_ReactionSpeed)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Secondary_DimensionalPocketCapacity)

/** Declares the "Tertiary Attributes" gameplay tag. */
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Tertiary_Level)

/** Declares the "Attribute Modification Type" gameplay tag. */
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Modifer_Heal)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Modifer_Damage)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Modifer_HOT)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attributes_Modifer_DOT)

/** Declares the "Attribute Modification Type" gameplay tag. */
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Message_HealthPotion)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Message_ManaPotion)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Message_HealthCrystal)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Message_ManaCrystal)


//const FString Msg = FString::Printf(TEXT("GE Tag: %s), Tag.GetTagName())
//GEngine->AddOnScreenDebugMessage(1,8.f, FColor::Blue, Msg);
	